id: A05008636
base_file: fC9AA.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:55:36.883706
  last_modified_at: 2022-05-30 22:55:36.883714
