id: A05008636
base_file: fA62E.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:55:36.879447
  last_modified_at: 2022-05-30 22:55:36.879454
